name: pawani
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  luthor: ^0.2.2
  luthor_annotation: ^0.2.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.2.0
  luthor_generator: ^0.3.1

flutter:
  uses-material-design: true
